### ISSUE TITLE
Uwagi

### ISSUE THREAD

**Issue by MarcinCiura** [nataliab9910/Tic-Tac-Toe_Python#1]
Pani kod wygląda całkiem porządnie. Moje uwagi są głównie kosmetyczne.

1. Przyjęło się wymieniać użyte biblioteki zewnętrzne (czyli `pygame`) w pliku `requirements.txt` (składnię sobie Pani znajdzie). Dzięki temu użytkownik może je zainstalować przez `pip install -r requirements.txt`

2. Nie przepadam za importowaniem klas/funkcji z modułów, bo to zaśmieca przestrzeń nazw. Lepsze jest importowanie całych modułów i pisanie np. `game.Game` ([punkt 2.2](https://google.github.io/styleguide/pyguide.html#22-imports)).

3. Lepiej, żeby konstruktory zajmowały się tylko dodawaniem pól do `self`, czyli np. z `Window.__init__()` przeniósłbym `pygame.display.set_caption("Tic-Tac-Toe Game!")` do funkcji wywołującej ten konstruktor.

4. Wyraz "actual" znaczy "rzeczywisty". "Bieżący" to "current". Zamiast komentarza przy deklaracji tej zmiennej lepiej napisać gdzieś u góry modułu `HUMAN, COMPUTER = range(2)` i używać tych stałych.

5. Pole `current_player` powinno być inicjalizowane w konstruktorze, a nie wewnątrz definicji klasy `Game`. Dzięki temu będzie miało osobną, a nie współdzieloną wartość w każdym obiekcie tej klasy, jeśli byłoby ich więcej. Wtedy `Game.flip_player()` itp. przestaną być metodami "klasowymi". Zamianę gracza można uzyskać np. przez `self.current_player = {COMPUTER: HUMAN, HUMAN: COMPUTER}[self.current_player]` lub w dowolny inny sposób.

6. Zamiast `Window.run_window()` wystarczy `Window.run()`.

7. Ogólniej by było zamiast jednego `SIZE` mieć osobne `BOARD_WIDTH` i `BOARD_HEIGHT`. Jedno z nich byłoby przekazywane jako drugi argument do `Window.get_number()`.

8. Zwracanie `-1` z `Window.get_number()` bez reagowania na tę wartość w miejscach wywołania jest niebezpieczne. Teraz jeśli kliknę np. w drugim wierszu, ale poza kolumnami, zostanie to zaliczone jako pierwszy wiersz i najbardziej prawa kolumna.

9. Stałe `(200, 100, 100)`, `lines = ...`, `(0, 0, 0)` i `2` proszę nazwać  `WINDOW_COLOR`, `LINES`, `LINE_COLOR` i `LINE_WIDTH` i przenieść do góry modułu.

10. Funkcję `main()` przepisałbym jak niżej i usunął ślady zbędnej funkcji `board_loop()`.
```python
def main():
    pygame.init()
    pygame.display.set_caption(...)
    window = window.Window()
    window.draw_lines()
    window.run()
```

**Comment by MarcinCiura** [comment]
Jeśli AI działa jak trzeba, to gratuluję Pani — po uwzględnieniu poniższych uwag i dopisaniu testu będzie po wszystkim.

1. [Tu](https://github.com/nataliab9910/Tic-Tac-Toe_Python/blob/ff6ee347afd34c8fa7fa7753552294bb9d284646/game.py#L31) lepiej `BOARD[:]`, co tworzy kopię. Tak, jak jest teraz, `Game` bazgrze po jedynej `BOARD` w programie (Co by było, gdyby zrobić dwa obiekty `Game`, nawet niekoniecznie w tym samym czasie, tylko jeden po drugim? To się całkiem normalnie zdarza przy testach).
2. [Tutaj](https://github.com/nataliab9910/Tic-Tac-Toe_Python/blob/ff6ee347afd34c8fa7fa7753552294bb9d284646/game.py#L90) `self.board[:]` też będzie lepiej wyglądać.
3. [Ta metoda](https://github.com/nataliab9910/Tic-Tac-Toe_Python/blob/ff6ee347afd34c8fa7fa7753552294bb9d284646/game.py#L68) wydaje mi się zbędna. Zwykłe odczytywanie `self.CURRENT_PLAYER` powinno wystarczyć.

**Comment by nataliab9910** [comment]
Dziękuję bardzo za uwagi, uwzględniłam je w projekcie. Dodatkowo dopracowałam grę samą w sobie, dodając możliwość wyboru pierwszego gracza oraz rozpoczęcia nowej gry, gdy nastąpi wygrana.

AI, przynajmniej według mnie, działa prawidłowo - aktualnie ograniczyłam czas "myślenia" komputera do 5 sekund, w ciągu których zazwyczaj zdąża ocenić ok. 6 kolejnych ruchów, dzięki czemu skutecznie wygrywa każdą rozgrywkę. Poza tym, aby gra nie przebiegała za każdym razem tak samo, pola planszy, na których można umieścić pionek, są przeglądane w kolejności losowej - dzięki temu, nawet jeśli rozstawienie pionków w kolejnych rozgrywkach jest identyczne, to komputer może wykonać inny ruch, jeśli jest on równie dobry. 

Teraz zajmę się dopisaniem testu.

**Comment by MarcinCiura** [comment]
Dziękuję za wiadomość. Parę drobnych uwag poniżej.
1. `requirements.txt`, nie `requirements`.
2. [Tutaj](https://github.com/nataliab9910/Tic-Tac-Toe_Python/blob/b6283b2db7510412642b472a889b696f911caed5/window.py#L29) `os.path.join()` nie ma sensu. Pisać po prostu `'O.png'`.
3. [Tutaj](https://github.com/nataliab9910/Tic-Tac-Toe_Python/blob/b6283b2db7510412642b472a889b696f911caed5/game.py#L131) otoczyć warunek nawiasami i zlikwidować `\` (2. rozdział).
4. [Tutaj](https://github.com/nataliab9910/Tic-Tac-Toe_Python/blob/b6283b2db7510412642b472a889b696f911caed5/game.py#L124) zamiast słownika, lepiej napisać wyżej
```python
class Waiting:
    def __init__(self):
        self.expected = 0
        ...
```
i używać obiektu tej klasy zamiast słownika.
5. Stałe 3 i 9 ponazywać (2. rozdział).

**Comment by nataliab9910** [comment]
Dziękuję za uwagi, wprowadziłam poprawki. 

Napisałam również kilka testów do algorytmu minimax, jednak nie jestem pewna, czy rozdzielanie ich na sprawdzanie ruchów komputera, gdy istnieje możliwość wygranej bądź ryzyko przegranej kolejno w rzędzie, kolumnie i na przekątnej ma sens, czy raczej zamiast tego powinnam przetestować w podobny sposób metodę check_winner.

**Comment by MarcinCiura** [comment]
Dziękuję za wiadomość. Testy są OK; na zaliczenie więcej nie potrzeba. To dobrze, że minimax jest przetestowany. Testowanie metody `.check_winner()` przydałoby się niezależnie. Ale — jak wyżej — nie zmieniłoby to Pani oceny (5). Podobnie — dla Pani wiadomości — podaję, że minimax można zastąpić algorytmem alfa-beta (parę wierszy więcej) bez większej zmiany sposobu jego wywoływania. Dzięki takiej zmianie głębokość przeszukiwania w 5 sekund powinna osiągnąć około 10 półruchów, a obecna głębokość 6 półruchów powinna być osiągana w ułamku sekundy.

1. [Dziwne formatowanie](https://github.com/nataliab9910/Tic-Tac-Toe_Python/blob/b549fd2c261876e1f6bf4a41b2ddf855291aca7f/game_test.py#L43) można poprawić np. tak:
```python
self.assertIn(
    self.game.board,
    ([...,
      ...,
      ...],
     [...,
      ...,
      ...]))
```
2. [Kolory](https://github.com/nataliab9910/Tic-Tac-Toe_Python/blob/b549fd2c261876e1f6bf4a41b2ddf855291aca7f/window.py#L41) itp. stałe lepiej nazywać wg zastosowania, nie zawartości (2. rozdział, 5. punkt).
3. [Po tym wierszu](https://github.com/nataliab9910/Tic-Tac-Toe_Python/blob/b549fd2c261876e1f6bf4a41b2ddf855291aca7f/game.py#L187) wystarczy napisać `random.shuffle(empty_positions)` i potem `for ... in empty_positions:`. Wyżej też.

**Comment by nataliab9910** [comment]
Dziękuję za uwagi, uwzględniłam je w projekcie.

**Comment by MarcinCiura** [comment]
LGTM. Gratuluję pracowitości, jest Pani siódma.
[To](https://github.com/nataliab9910/Tic-Tac-Toe_Python/blob/da426c5405f5752620cc68dc5baa683d882d8d91/game.py#L18) pomyłka?

**Comment by nataliab9910** [comment]
Dziękuję bardzo 😊

Tak, to moja pomyłka. Upewniałam się, że wszystko zadziała również wtedy, gdy graczowi uda się wygrać z komputerem. Już poprawiłam.
